beisia_app/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
        ),
]# -*- coding: utf-8 -*-

beisia_app/basia_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('memo/', include('memo.urls')),
]

beisia_app/memo/urls.py
from django.urls import path
from . import views

app_name = 'memo'
urlpatterns = [
    path('create', views.ListsCreateView.as_view(), name='create'),    
    path('create/<int:year>/<int:month>/<int:day>/', views.ListsCreateView.as_view(), name='create'),
    path('thanks', views.thanks, name='thanks'),
    path('lists', views.Search.as_view(), name='lists'),
    path('okaimono/<int:num>', views.okaimono, name='okaimono'),
    path('edit/<int:num>', views.edit, name='edit'),
]

beisia_app/app/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('名前', max_length=50)
    description = models.TextField('買ってきてほしいもの', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

# Create your models here.

beisia_app/memo/models.py
from django.db import models

class Lists(models.Model):
    date = models.CharField(max_length=50,null=True)
    name = models.CharField(max_length=50)
    number = models.IntegerField()
    phone = models.IntegerField(null=True)
    lists = models.TextField()
    
    def __str__(self):
        return '<Lists:name=' + str(self.name) + ',' + \
              str(self.date)  + '>'
    

beisia_app/app/forms.py
from django import forms
from .models import Schedule


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time
# -*- coding: utf-8 -*-

beisia_app/memo/forms.py
from django import forms
from .models import Lists

class ListsForm(forms.ModelForm):
    class Meta:
        model = Lists
        fields = ['date', 'name','number','phone','lists']
        labels = {
                'date':'日付',
                'name':'お名前',
                'number':'学籍番号',
                'phone' : '電話番号',
                'lists':'買い物リスト',
            }
        widgets={'date':forms.TextInput(attrs={'placeholder':''})}
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
        '''def __init__(self, *args, **kwargs):
            super(ListsForm, self).__init__(*args, **kwargs)
            self.fields['date'].initial = 5'''
            

beisia_app/app/views.py
import datetime
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm
from .models import Schedule
'''from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import ListsForm
from .models import Lists'''
...
...

def index(request):
    params = {
            'title':'ベイシア便オンラインサービス',
    }
    return render(request, 'app/home.html', params)


class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'app/mycalendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        """week_calendar_context = self.get_week_calendar()"""
        month_calendar_context = self.get_month_calendar()
        """context.update(week_calendar_context)"""
        context.update(month_calendar_context)
        return context

    def form_valid(request, self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('memo:create', year=date.year, month=date.month, day=date.day)
        
'''def test(request, year, month, day):
    params = {
            'year1' : year,
            'month1' : month,
            'date1' : day,
    }
    return render(request, 'app/test.html', params)'''


    
    
# Create your views here.

beisia_app/memo/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from .forms import ListsForm
from .models import Lists
from django.db.models import Q


class ListsCreateView(CreateView):
    template_name = 'memo/create.html'
    form_class = ListsForm
    model = Lists
    success_url = reverse_lazy('memo:thanks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['year'] = self.kwargs.get('year')
        context['month'] = self.kwargs.get('month')
        context['day'] = self.kwargs.get('day')
        context['form'] = ListsForm( initial = {'date':str(context['year']) + '/' + str(context['month']) + '/' + str(context['day'])} )
        return context
    
    
    def form_valid(self, form):
        ctx = {'form': form }
        if self.request.POST.get('next', '') == 'confirm':
            return render(self.request, 'memo/confirm.html', ctx)
        if self.request.POST.get('next', '') == 'back':
            return render(self.request, 'memo/create.html', ctx)
        if self.request.POST.get('next', '') == 'create':
            return super().form_valid(form)
        else:
            return redirect(reverse_lazy('memo:create'))
        
def thanks(request):
    return render(request, 'memo/thanks.html')
    
class Search(ListView):
    model = Lists
    
    def get_queryset(self):
        q_word = self.request.GET.get('query')
 
        if q_word:
            object_list = Lists.objects.filter(
                Q(name__icontains=q_word) | Q(number__icontains=q_word))
        else:
            object_list = Lists.objects.none()
        return object_list

def okaimono(request, num): 
    obj = Lists.objects.get(id=num)
    params = {
            'id':num,
            'form':ListsForm(instance=obj),
            }
    return render(request, 'memo/okaimono.html', params)

def edit(request, num):
    obj = Lists.objects.get(id=num)
    if (request.method == 'POST'):
        lists = ListsForm(request.POST, instance=obj)
        lists.save()
        return redirect('memo:okaimono', num)
    params = {
            'title' : 'edit',
            'id' : num,
            'form' : ListsForm(instance=obj),
    }
    return render(request, 'memo/edit.html', params)

beisia_app/app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/calenderstyle.css' %}">
    

</head>
<body>

<div class="container" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

beisia_app/app/templates/app/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/homestyle.css' %}">
    <meta charset="utf-8">
    <title>{{title}}</title>
</head>
<body>
    <div>
        <img class="beisia" src="{% static "app/images/beisia_title.png" %}" >
        <img class="car" src="{% static "app/images/car.png" %}" >
    </div>
    <input type="button" onclick="location.href='/mycalendar'" value="START" class="buttonL">
    <input type="button" onclick="location.href='/memo/lists'" value="確認" class="buttonR"></a>

</body>
</html>

beisia_app/app/templates/app/includes/month.html
<a href="{% url 'app:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<!--<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>-->
<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" border="1" height="600" width="800">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}
                {% if day < now %}
                    <a>{{ day.day }}</a>
                {% else %}
                    <a href="{% url 'memo:create' day.year day.month day.day %}" onclick="return confirm('この日付でよろしいですか？')">{{ day.day }}</a>
                {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

beisia_app/app/templates/app/mycalendar.html
{% extends 'app/base.html' %}
{% block content %}
    <p>食材を買ってきてほしい日を選択してください。</p>
    <div class="row">
            {% include 'app/includes/month.html' %}
            <hr>
    </div>
{% endblock %}


<!--
{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}
//-->

beisia_app/app/templates/app/test.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>test</title>
</head>
<body>
    <h1>hello</h1>
    <a>{{year1}}</a>
    <a>{{month1}}</a>
    <a>{{date1}}</a>
</body>
</html>

beisia_app/memo/templates/memo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'memo/css/memostyle.css' %}">
    <meta charset="utf-8">
    <title>買い物リスト</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

beisia_app/memo/templates/memo/confirm.html
{% extends 'memo/base.html' %}

{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a class="active section"></a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>買い物リスト作成</h3></div>
                <p>内容にお間違えはありませんか。</p>
                <table  class="ui celled table table table-hover" >
                    <tr><td>日付</td><td class="value">{{form.date.value}}</td></tr>
                    <tr><td>お名前</td><td class="value">{{form.name.value}}</td></tr>
                    <tr><td>学籍番号</td><td class="value">{{form.number.value}}</td></tr>
                    <tr><td>電話番号</td><td class="value">{{form.phone.value}}</td></tr>                    
                    <tr><td>買い物リスト</td><td class="value" ><pre>{{form.lists.value}}</pre></td></tr>
                </table>
                <form class="ui form" action="{% url 'memo:create' %}" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        {{field.as_hidden}}
                    {% endfor %}
                    <button class="buttonL" type="submit" name="next" value="back">戻る</button>
                    <button class="buttonR" type="submit" name="next" value="create">作成</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

beisia_app/memo/templates/memo/create.html
{% extends 'memo/base.html' %}

{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a class="active section"></a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>買い物リスト作成</h3></div>
                <form class="" action="{% url 'memo:create' %}" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="button1" name="next" value="confirm">作成</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

beisia_app/memo/templates/memo/edit.html
{% extends 'memo/base.html' %}

{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a class="active section"></a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>買い物リスト変更</h3></div>
                <form class="" action="{% url 'memo:edit' id %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="buttonR" value="click">更新</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

beisia_app/memo/templates/memo/lists_list.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'memo/css/liststyle.css' %}">
    <meta charset="utf-8">
    <title>予約確認</title>
</head>
<body>
    <h1>予約確認</h1>
    <p>{{message|safe}}</p>
    <a>氏名、または学籍番号を入力してください</a>
    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}"  typr="text">
        <button type="submit">検索する</button>
    </form>
    
    {% for item in object_list %}
    <table>
        <tr>
            <th>名前</th>
            <th>日付</th>

        </tr>
        <tr>
            <td>{{item.name}}</td>
            <td>{{item.date}}</td>
            <td><a href="{% url 'memo:okaimono' item.id %}">確認</a></td>
        <tr>
    {% endfor %}
    </table>
    <a href="{% url 'app:home' %}"><button type="submit" class="back">戻る</button></a>

</body>
</html>

beisia_app/memo/templates/memo/okaimono.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'memo/css/memostyle.css' %}">
    <meta charset="utf-8">
    <title>お買い物内容確認画面</title>
</head>
<body>
    <h1 class="check">予約確認</h1>
    <table class="okaimono">
        <tr><td>日付</td><td class="value">{{form.date.value}}</td></tr>
        <tr><td>お名前</td><td class="value">{{form.name.value}}</td></tr>
        <tr><td>学籍番号</td><td class="value">{{form.number.value}}</td></tr>
        <tr><td>電話番号</td><td class="value">{{form.phone.value}}</td></tr>        
        <tr><td>買い物リスト</td><td class="value" ><pre>{{form.lists.value}}</pre></td></tr>
    </table>
    <a href="{% url 'memo:lists' %}"><button type="submit" class="buttonL">戻る</button></a>
    <a href="{% url 'memo:edit' id %}"><button type="submit" class="buttonR">変更</button></a>

</body>
</html>

beisia_app/memo/templates/memo/record.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'memo/css/recordstyle.css' %}">
    <meta charset="utf-8">
    <title>予約確認</title>
</head>
<body>
    <h1>予約確認</h1>
    <p>{{message|safe}}</p>
    <table>
    <form action="{% url 'memo:record' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value="click"></td></tr>
    </form>
    </table>
    {% for item in data %}
    <table>
        <tr>
            <th>名前</th>
            <th>日付</th>

        </tr>
        <tr>
            <td>{{item.name}}</td>
            <td>{{item.date}}</td>
            <td><a href="{% url 'memo:okaimono' item.id %}">確認</a></td>
        <tr>
    {% endfor %}
    </table>
    <a href="{% url 'app:home' %}"><button type="submit">戻る</button></a>

</body>
</html>

beisia_app/memo/templates/memo/thanks.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
        <link rel="stylesheet" type="text/css" href="{% static 'memo/css/thanksstyle.css' %}">
    <meta charset="utf-8">
    <title>thanks</title>
</head>
<body>
    <div>
        <img class="beisia" src="{% static "memo/images/beisia_title.png" %}" >
    </div>
    <h1 class="thanks">ご予約ありがとうございました！！</h1>
    <a href="{% url 'app:home' %}">
      <button type="submit" value="thanks" >トップに戻る</button>
    </a>
</body>
</html>